/**
 * This file was generated by the JPA Modeler
 */
package com.talcorp.piecedetachee.jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author Taleb
 */
@Entity
@Table(name = "categories")
@NamedQueries({
    @NamedQuery(name = "Categorie.findAll", query = "SELECT c FROM Categorie c"),
    @NamedQuery(name = "Categorie.findById", query = "SELECT c FROM Categorie c WHERE c.id = :id"),
    @NamedQuery(name = "Categorie.findByTitreCategorie", query = "SELECT c FROM Categorie c WHERE c.titreCategorie = :titreCategorie")})
@XmlRootElement
public class Categorie implements Serializable {

    @Column(name = "ID")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "TITRE_CATEGORIE")
    @Basic
    private String titreCategorie;

    @Lob
    @Basic(fetch = FetchType.LAZY)
    private byte[] logo;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitreCategorie() {
        return this.titreCategorie;
    }

    public void setTitreCategorie(String titreCategorie) {
        this.titreCategorie = titreCategorie;
    }

    public byte[] getLogo() {
        return this.logo;
    }

    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

}
