/**
 * This file was generated by the JPA Modeler
 */
package com.talcorp.piecedetachee.jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Taleb
 */
@Embeddable
public class Coordonnee implements Serializable {

    @Basic
    private String adresse;

    @Basic
    private String telephone;

    @Basic
    private String email;

    public String getAdresse() {
        return this.adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
