/**
 * This file was generated by the JPA Modeler
 */
package com.talcorp.piecedetachee.jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author Taleb
 */
@Embeddable
public class DetailProduit implements Serializable {

    @Basic
    private String NumeroLot;

    @Basic
    private String NumeroSerie;

    public String getNumeroLot() {
        return this.NumeroLot;
    }

    public void setNumeroLot(String NumeroLot) {
        this.NumeroLot = NumeroLot;
    }

    public String getNumeroSerie() {
        return this.NumeroSerie;
    }

    public void setNumeroSerie(String NumeroSerie) {
        this.NumeroSerie = NumeroSerie;
    }

}
