//
// This file was generated by the JPA Modeler
//
package com.talcorp.piecedetachee.jpa.entities;

import java.io.Serializable;
import java.util.Objects;

/**
 *
 * @author $author
 */
public class FacturePK implements Serializable {

    private Integer id;

    private Integer fournisseur;

    public FacturePK() {

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getFournisseur() {
        return this.fournisseur;
    }

    public void setFournisseur(Integer fournisseur) {
        this.fournisseur = fournisseur;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + Objects.hashCode(this.id);
        hash = 59 * hash + Objects.hashCode(this.fournisseur);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FacturePK other = (FacturePK) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.fournisseur, other.fournisseur)) {
            return false;
        }
        return true;
    }

}
