/**
 * This file was generated by the JPA Modeler
 */
package com.talcorp.piecedetachee.jpa.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author Taleb
 */
@Entity
@Table(name = "factures")
@IdClass(FacturePK.class)
@NamedQueries({
    @NamedQuery(name = "Facture.findAll", query = "SELECT f FROM Facture f"),
    @NamedQuery(name = "Facture.findById", query = "SELECT f FROM Facture f WHERE f.id = :id"),
    @NamedQuery(name = "Facture.findByDate", query = "SELECT f FROM Facture f WHERE f.date = :date"),
   // @NamedQuery(name = "Facture.findByIdFournisseur", query = "SELECT f FROM Facture f WHERE f.idFournisseur = :idFournisseur"),
    @NamedQuery(name = "Facture.findByMontantGlobal", query = "SELECT f FROM Facture f WHERE f.montantGlobal = :montantGlobal")})
@XmlRootElement
public class Facture implements Serializable {

    @Column(name = "ID")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "DATE")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date date;

    @Column(name = "MONTANT_GLOBAL")
    @Basic
    private Integer montantGlobal;

    @Basic
    private String numeroFacture;

    @Id
    @OneToOne(targetEntity = Fournisseur.class)
    private Fournisseur fournisseur;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Integer getMontantGlobal() {
        return this.montantGlobal;
    }

    public void setMontantGlobal(Integer montantGlobal) {
        this.montantGlobal = montantGlobal;
    }

    public String getNumeroFacture() {
        return this.numeroFacture;
    }

    public void setNumeroFacture(String numeroFacture) {
        this.numeroFacture = numeroFacture;
    }

    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }

    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }

}
