/**
 * This file was generated by the JPA Modeler
 */
package com.talcorp.piecedetachee.jpa.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author Taleb
 */
@Entity
@Table(name = "vente")
@NamedQueries({
    @NamedQuery(name = "Vente.findAll", query = "SELECT v FROM Vente v"),
    @NamedQuery(name = "Vente.findById", query = "SELECT v FROM Vente v WHERE v.id = :id"),
//    @NamedQuery(name = "Vente.findByIdProduit", query = "SELECT v FROM Vente v WHERE v.idProduit = :idProduit"),
    @NamedQuery(name = "Vente.findByPrixFinal", query = "SELECT v FROM Vente v WHERE v.prixFinal = :prixFinal"),
    @NamedQuery(name = "Vente.findByDateVente", query = "SELECT v FROM Vente v WHERE v.dateVente = :dateVente")})
@XmlRootElement
public class Vente implements Serializable {

    @Column(name = "ID")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "PRIX_FINAL")
    @Basic
    private Integer prixFinal;

    @Column(name = "DATE")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateVente;

    @Basic
    private String quantiteVendu;

    @OneToMany(targetEntity = Approvisionement.class)
    private List<Approvisionement> approvisionements;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPrixFinal() {
        return this.prixFinal;
    }

    public void setPrixFinal(Integer prixFinal) {
        this.prixFinal = prixFinal;
    }

    public Date getDateVente() {
        return this.dateVente;
    }

    public void setDateVente(Date dateVente) {
        this.dateVente = dateVente;
    }

    public String getQuantiteVendu() {
        return this.quantiteVendu;
    }

    public void setQuantiteVendu(String quantiteVendu) {
        this.quantiteVendu = quantiteVendu;
    }

    public List<Approvisionement> getApprovisionements() {
        return this.approvisionements;
    }

    public void setApprovisionements(List<Approvisionement> approvisionements) {
        this.approvisionements = approvisionements;
    }

}
